name: wisqu
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  frosted_glass_effect: ^0.0.2
  glassmorphism: ^3.0.0
  flutter_svg: ^2.2.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1  # نسخه جدید

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/google-logo.png
    - assets/icons/
    - assets/fonts/
    - assets/gradient.png

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/opensans/OpenSans-bold.ttf
          weight: 700
        - asset: assets/fonts/opensans/OpenSans-light.ttf
          weight: 300
        - asset: assets/fonts/opensans/OpenSans-regular.ttf
          weight: 400
        - asset: assets/fonts/opensans/OpenSans-semibold.ttf
          weight: 600
    - family: Estedad
      fonts:
        - asset: assets/fonts/estedad/Estedad-FD-Regular.ttf
          weight: 400
        - asset: assets/fonts/estedad/Estedad-FD-Bold.ttf
          weight: 700
        - asset: assets/fonts/estedad/Estedad-FD-ExtraBold.ttf
          weight: 800

# تنظیمات جدید — در سطح اصلی فایل
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21